spring:
  profiles:
    active: dev
#    active: prod
  http:
  multipart:
  maxFileSize: 2MB
server:
  port: 8092
  tomcat:
    uri-encoding: UTF-8
    max-threads: 20000        #最大并发数
    max-connections: 200000   #接受和处理的最大连接数
    min-SpareThreads: 200     #初始化时创建的线程数
    acceptCount: 7000         #可以放到处理队列中的请

servlet:
  multipart:
    # 上传文件总的最大值
      max-request-size: 10MB
   # 单个文件的最大值
      max-file-size: 10MB

